### ISSUE TITLE
Bug in networking.go DialTCP() 

### ISSUE THREAD

**Issue by bytesundso** [xrjr/mcutils#29] opened 2022-12-14 10:10 UTC
When you call client.Ping it can crash in net.LookupSRV("minecraft", "tcp", hostname)

**Comment by xrjr** [comment] 2022-12-14 13:19
Hello,

I don't know why you removed informations from your comment, but anyway. If any error occurs during the SRV lookup process, or if no record is returned, it will simply go next and use given hostname/address to dial. This is the expected behavior.

This behavior is safe, as it doesn't access lookup result if there was an error. But I may be wrong, and if you encountered a crash because of it, feel free to open a new issue. Don't forget to write as much informations and details as possible. I always make sure to fix incorrect behaviors as fast as possible.

I will close this issue for now.

**Closed as completed by xrjr** 2022-12-14 13:19 UTC
