### ISSUE TITLE
Raw ping response for legacy servers

### ISSUE THREAD

**Issue by MrMarble** [xrjr/mcutils#16] opened 2022-05-26 17:08 UTC
As stated in the Wiki, a server running Forge will add additional information about the installed mods, https://wiki.vg/Minecraft_Forge_Handshake.

On the latest versions you can access it using the `ping.JSON` map, but for legacy servers the handshake is parsed into `ping.LegacyPingInfos` without the option of getting the raw map response.

Thank you so much for all the work!

**Comment by xrjr** [comment] 2022-05-27 18:05
In pre 1.7 SLP protocol, informations aren't sent through JSON format but rather through bytes-encoded values. All informations that the response contains are decoded into the `ping.LegacyPingInfos`. There is no such raw map response.

[See 1.6 section of the wiki](https://wiki.vg/Server_List_Ping#1.6)


I may be wrong, but AFAIK legacy forge servers implement SLP just as regular Minecraft servers do. On those servers, if you want to get the mod list, you have to implement the handshake sequence, which occurs after the login sequence, etc...

Thank you for your support and feedback !

**Comment by MrMarble** [comment] 2022-05-28 07:57
You're right, my bad.
Then there must be something wrong, or I'm not understanding something...
I made some testing with this server `naruto.apollonetworkmc.net`, using mcsrvstat you can see all the information: https://mcsrvstat.us/server/naruto.apollonetworkmc.net

Server is running 1.7.10, so I guess I have to use the `ping.Ping()` method to do a SLP but that returns an error: (example using the CLI, does the same as a library)
```sh
mcutils ping naruto.apollonetworkmc.net 25565
Error : invalid packet type.
Usage : mcutils ping <hostname> <port>
```
Because of that, I tried the legacy (both `legacy` and `legacy-1.6.4`) and this is the response:
```sh
mcutils ping-legacy naruto.apollonetworkmc.net 25565
{
        "protocolVersion": 127,
        "minecraftVersion": "1.7.10",
        "motd": "Naruto Apollo",
        "onlinePlayers": 9,
        "maxPlayers": 100
}
Latency : 114 ms
```

Maybe the error is in the `ping.Ping` method not understanding the Forge Handshake and I thought it was the server having an old version

**Comment by xrjr** [comment] 2022-05-28 15:46
Thank you for your detailed description. I'll take a further look at it when I have time (probably next week).

Be sure that if it's not a forge issue, it will be fixed soon.

**Comment by MrMarble** [comment] 2022-05-29 10:10
I tried using this library https://github.com/Tnze/go-mc and was able to do a successful Server list ping to that server following the mcping example https://github.com/Tnze/go-mc/tree/master/examples/mcping.

I think that clarifies that the Server is responding correctly and is indeed a bug in the implementation

**Comment by xrjr** [comment] 2022-05-29 16:34
Ok I took a look at it, and it appears that this is not a bug in the client implementation. Forge servers (or at least this one) respond to `Ping` packet by a `Handshake` response ([see Handshake and Ping sections of this page](https://wiki.vg/Server_List_Ping)). When parsing pong response, the `PingClient` reads the packet id, get `0` instead of `1`, and returns an error. This is clearly the intended behavior.

Because of this sentence of the wiki, we have to send the following `Ping` packet in the `ping.Ping` function :

> Note that Notchian servers will for unknown reasons wait to receive the following [Ping](https://wiki.vg/Protocol#Ping) packet for 30 seconds before timing out and sending Response.

And at this point, this line of the documentation prevents me from returning handshake informations even if there is an error on ping request :

> If an error occured at any point of the process, an nil json response, a latency of -1, and a non nil error are returned.

I may change this behavior in a future release, but for now if you want to use `mcutils` in your case, your best bet is to use the `ping.PingClient` as described in the README, without performing the `Ping` request (only `Handshake`).

`Onze/go-mc` doesn't check for the packet id, this is the reason why it technically works. I don't want `mcutils` to parse the wrong packet format, because it can lead to unintended behaviors (e.g. read timeout). In this case, this is not a problem because the expected data type (a long) is shorter than the received data (a string containing all informations), but it could have been if it was the other way.

**Comment by xrjr** [comment] 2022-05-29 17:11
Ok `v1.2.3` should "fix" this.

`ping.Ping` function now ignores the `ErrInvalidPacketType` error from the `ping.PingClient.Ping` function, and the latency is returned even if parsing isn't done properly.

Fell free to give me your feedback on this feature.

**Closed as completed** 2022-08-10 06:12 UTC
